backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Content Key", name: "contentKey", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pageData/index.md"
        label: "Index Page"
        name: "index-page"
        fields:
          - { label: "Tagline", name: "tagline", widget: "string" }
          - { label: "Image 1", name: "image1", widget: "image" }
          - { label: "Image 2", name: "image2", widget: "image" }
          - { label: "Image 3", name: "image3", widget: "image" }
      - file: "src/pageData/menu.md"
        label: "Menu"
        name: "menu"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - label: "Categories"
            label_singular: "Category"
            name: "categories"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - label: "Items"
                label_singular: "Item"
                name: "items"
                widget: "list"
                fields:
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "Price", name: "price", widget: "string" }
